image: python:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYPI_INDEX: "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/api/v4/groups/${CI_PROJECT_NAMESPACE}/-/packages/pypi/simple"
  PIPX_BIN_DIR: "/usr/local/bin"

cache:
  paths:
    - .venv

# Install Python deps
before_script:
  - python -m pip install --upgrade pip pipx
  - pipx install poetry
  - poetry config virtualenvs.in-project true
  - poetry config repositories.chipflow https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
  - poetry config http-basic.chipflow gitlab-ci-token ${CI_JOB_TOKEN}

dist:
  except:
    - merge_requests
  script:
    - poetry self add "poetry-dynamic-versioning[plugin]"
    - poetry build
    - poetry publish --repository chipflow

dist-test:
  only:
    - merge_requests
  script:
    - poetry self add "poetry-dynamic-versioning[plugin]"
    - poetry build
 
